# Generated by Django 5.1.3 on 2024-11-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='latitud',
            field=models.FloatField(default=4.6014026),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitud',
            field=models.FloatField(default=-74.0660152),
        ),
    ]
